import  pygame
import random
import time

#Constantes Numéricas:
TELA_MENU_LARGURA = 1000
TELA_MENU_ALTURA = 800
FONTE_TITULO = 30
FONTE_TEXTO = 10
FONTE_MAIN_MENU = 100
FONTE_BOTOES = 75
FONTE_BACK = 50
FONTE_SCORE = 15
VELOCIDADE_INICIAL = 0
VELOCIDADE_FINAL_MENU = 20
VELOCIDADE_JOGADOR = 2
CENTRALIZACAO_X = 0
CENTRALIZACAO_Y = 0
INCREMENTO_VELCOCIDADE_MENU = 1
INCREMENTO_DIFICULDADE = 10
OPTIONS_X = 510
OPTION_Y_1 = 150
OPTION_Y_2 = 320
OPTION_Y_3 = 480
OPTION_Y_4 = 550
RETANGULO_X = 500
RETANGULO_Y_1 = 15
RETANGULO_Y_2 = 60
RETANGULO_Y_3 = 80
RETANGULO_Y_4 = 100
RETANGULO_Y_5 = 600
SCORE_X = 800
SCORE_Y = 10
TEMPO_ANIMACAO = 0.25
CORRECAO_SEGUNDOS = 1000
ARREDONDAMENTO = 3
DIFICULDADE_INICIAL = 50
NUMERO_RETANGULOS = 30
COLUNAS = 5
LINHAS= 5
LARGURA_RETANGULO_MAR = 50
ALTURA_RETANGULO_MAR = 50

#Constantes Load:
BACKGROUND = pygame.image.load("imagens/pirate-treasure-island.png")
ILHA_FUNDO = pygame.image.load("imagens/73c76382909a6305111caddf2bdb09a6 (1).png")
MUSICA_MENU = "audios/Sea waves with birds - Sound Effect [HQ] [TubeRipper.com].ogg"
MUSICA_JOGO = "audios/Mutiny Pirate Survival RPG Soundtrack - Ape Island Theme - Track 15 - Island of the Apes [TubeRipper.com].ogg"
FONTE_PADRAO = "assets/font.ttf"
FONTE_ARIAL = "Arial"
RETANGULO_PLAY = "assets/Play Rect.png"
RETANGULO_OPTIONS = "assets/Options Rect.png"
RETANGULO_QUIT = "assets/Quit Rect.png"


#Constantes Textos:
NOME_JOGO = "Projeto Algoritmos em Grafos"
TITULO = "Manual:"
VOLTAR = "VOLTAR"
PARAGRAFO_1 = "teste"
PARAGRAFO_2 = "teste"
PARAGRAFO_3 = "teste"
MENU = "MENU"
JOGAR = "JOGAR"
MANUAL = "MANUAL"
SAIR = "SAIR"

#Cores:
BRANCO = "#FFFFFF"
PRETO = "#000000"
VERDE = "#00FF00"
AMARELO = "#FFFF00"
VERDE_CLARO = "#d7fcd4"
VERMELHO = "#FF0000"
LARANJA = "#FF8000"
LARANJA_PERGUNTA = "#FFA500"
AZUL = "#0000FF"
AZUL_CLARO = "#69b4ff"
MARROM = "#a95e13"