import  pygame

#Constantes Numéricas:
TELA_MENU_LARGURA = 1000
TELA_MENU_ALTURA = 700
TELA_JOGO_LARGURA = 1024
TELA_JOGO_ALTURA = 500
FONTE_TITULO = 30
FONTE_TEXTO = 10
FONTE_MAIN_MENU = 100
FONTE_BOTOES = 75
FONTE_BACK = 50
FONTE_SCORE = 15
VELOCIDADE_INICIAL = 0
VELOCIDADE_FINAL_MENU = 20
VELOCIDADE_JOGADOR = 2
CENTRALIZACAO_X = 0
CENTRALIZACAO_Y = 0
INCREMENTO_VELCOCIDADE_MENU = 1
INCREMENTO_DIFICULDADE = 10
OPTIONS_X = 540
OPTION_Y_1 = 100
OPTION_Y_2 = 250
OPTION_Y_3 = 400
OPTION_Y_4 = 550
RETANGULO_X = 500
RETANGULO_Y_1 = 15
RETANGULO_Y_2 = 60
RETANGULO_Y_3 = 80
RETANGULO_Y_4 = 100
RETANGULO_Y_5 = 600
SCORE_X = 800
SCORE_Y = 10
TEMPO_ANIMACAO = 0.25
CORRECAO_SEGUNDOS = 1000
ARREDONDAMENTO = 3
DIFICULDADE_INICIAL = 50
NUMERO_RETANGULOS = 30

#Constantes Load:
BACKGROUND = pygame.image.load("imagens/pirate-treasure-island.png")
MUSICA_MENU = "audios/Sea waves with birds - Sound Effect [HQ] [TubeRipper.com].ogg"
MUSICA_JOGO = "audios/sea waves sound effects [TubeRipper.com].ogg"
FONTE_PADRAO = "assets/font.ttf"
FONTE_ARIAL = "Arial"
RETANGULO_PLAY = "assets/Play Rect.png"
RETANGULO_OPTIONS = "assets/Options Rect.png"
RETANGULO_QUIT = "assets/Quit Rect.png"


#Constantes Textos:
NOME_JOGO = "Projeto Algoritmos em Grafos"
TITULO = "Manual:"
VOLTAR = "VOLTAR"
PARAGRAFO_1 = "teste"
PARAGRAFO_2 = "teste"
PARAGRAFO_3 = "teste"
MENU = "MENU"
JOGAR = "JOGAR"
MANUAL = "MANUAL"
SAIR = "SAIR"

#Cores:
BRANCO = "#FFFFFF"
PRETO = "#000000"
VERDE = "#00FF00"
AMARELO = "#b68f40"
VERDE_CLARO = "#d7fcd4"
LARANJA = "#FF8000"